sudo: false

language: generic

env:
  - STACK_YAML=stack.yaml
  - STACK_YAML=ghc-802.yaml
  - STACK_YAML=ghc-822.yaml
  - STACK_YAML=ghc-841.yaml

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- stack --no-terminal --install-ghc test --haddock --no-haddock-deps
